import { createDefaultModule, DefaultModuleContext, inject, LangiumServices, Module, PartialLangiumServices } from 'langium';
import { SecondGeneratedModule } from './generated/module';
import { SecondValidationRegistry, SecondValidator } from './second-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type SecondAddedServices = {
    validation: {
        SecondValidator: SecondValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type SecondServices = LangiumServices & SecondAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const SecondModule: Module<SecondServices, PartialLangiumServices & SecondAddedServices> = {
    validation: {
        ValidationRegistry: (injector) => new SecondValidationRegistry(injector),
        SecondValidator: () => new SecondValidator()
    }
};

/**
 * Inject the full set of language services by merging three modules:
 *  - Langium default services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 */
export function createSecondServices(context?: DefaultModuleContext): SecondServices {
    return inject(
        createDefaultModule(context),
        SecondGeneratedModule,
        SecondModule
    );
}
